array(37) { ["mycatid"]=> string(1) "0" ["typeid"]=> string(1) "0" ["title"]=> string(3) "123" ["level"]=> string(1) "0" ["style"]=> string(0) "" ["catid"]=> string(2) "20" ["totime"]=> string(1) "0" ["unit"]=> string(0) "" ["price"]=> string(1) "0" ["amount"]=> string(1) "0" ["username"]=> string(5) "admin" ["company"]=> string(0) "" ["areaid"]=> string(1) "0" ["truename"]=> string(0) "" ["mobile"]=> string(0) "" ["email"]=> string(0) "" ["telephone"]=> string(0) "" ["address"]=> string(0) "" ["status"]=> string(1) "3" ["note"]=> string(0) "" ["addtime"]=> string(10) "1482998627" ["template"]=> string(0) "" ["thumb"]=> string(0) "" ["thumb1"]=> string(0) "" ["thumb2"]=> string(0) "" ["filepath"]=> string(0) "" ["editor"]=> string(5) "admin" ["adddate"]=> string(10) "2016-12-29" ["edittime"]=> string(10) "1483001365" ["editdate"]=> string(10) "2016-12-29" ["fee"]=> string(1) "0" ["minamount"]=> string(1) "0" ["days"]=> string(1) "0" ["elite"]=> string(1) "0" ["introduce"]=> string(0) "" ["ip"]=> string(7) "unknown" ["content"]=> string(0) "" }

itemid
catid
mycatid
typeid
areaid
level
elite
title
style
fee
introduce
n1
n2
n3
v1
v2
v3
brand
unit
price
minamount
amount
days
tag
keyword
pptword
hits
thumb
thumb1
thumb2
username
groupid
company
vip
validated
truename
telephone
mobile
address
email
msn
qq
ali
skype
totime
editor
edittime
editdate
addtime
adddate
ip
template
status
linkurl
filepath
note
ticketcode
ticketpass
platform
kucun
issell
buyer

